### ISSUE TITLE
 ER_BAD_FIELD_ERROR: Unknown column 'skills_levels_modifiers.level_id' in 'where clause'

### ISSUE THREAD

**Issue by lendsp** [damian-pastorini/reldens#175]
**root@iZrj90s90xr5ub5kvqyojpZ:~/game/node_modules/reldens/migrations/production# npm install knex -g**
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

changed 177 packages, and audited 178 packages in 6s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
**root@iZrj90s90xr5ub5kvqyojpZ:~/game/node_modules/reldens/migrations/production# npm run install-db**

> reldens@4.0.0-beta.16.5 install-db
> knex migrate:up --env production

Working directory changed to ~/game
Using environment: production
Batch 1 ran the following migrations:
20190923181825_v4.0.0.js
**root@iZrj90s90xr5ub5kvqyojpZ:~/game/node_modules/reldens/migrations/production# cat 20190923181825_v4.0.0.js**
const fs = require('fs');

exports.up = function(knex) {
    let sql = fs.readFileSync(__dirname+'/reldens-install-v4.0.0.sql').toString();
    return knex.raw(sql);
};

// eslint-disable-next-line no-unused-vars
exports.down = function(knex) {
    // nothing to do in the first version.
};
**root@iZrj90s90xr5ub5kvqyojpZ:~/game/node_modules/reldens/migrations/production# cd ~
root@iZrj90s90xr5ub5kvqyojpZ:~# cd game/
root@iZrj90s90xr5ub5kvqyojpZ:~/game# npm start**

> reldens-skeleton@4.0.0-beta.16.5 start
> node .

INFO - [ 'Project root:',
  '/root/game',
  'Module root:',
  '/root/game/node_modules/reldens/packages/game/server' ]
INFO - [ 'DataServer Config:',
  { host: 'localhost',
    port: 3306,
    database: 'reldens',
    user: 'reldens',
    password: 'reldens',
    connectionLimit: 0 },
  { min: 2, max: 10 },
  'mysql://reldens:reldens@localhost:3306/reldens' ]
INFO - Objection JS ready!
Server starting...
INFO - Starting Server Manager!
INFO - [ 'Mailer Configured:', false ]
INFO - Enabled feature: chat
INFO - Enabled feature: respawn
INFO - Enabled feature: inventory
INFO - Enabled feature: firebase
INFO - Enabled feature: actions
INFO - Enabled feature: users
INFO - Events test reldens.serverConfigFeaturesReady success!
INFO - Loaded game room using stored configuration.
INFO - Loaded extra room: chat
INFO - Loaded room: ReldensHouse_1
INFO - Loaded room: ReldensHouse_2
INFO - Loaded room: ReldensTown
INFO - Loaded room: ReldensForest
INFO - Total rooms loaded: 5
INFO - Listening on http://localhost:8080
ERROR - Server error: { DBError: select `skills_levels_modifiers`.* from `skills_levels_modifiers` where `skills_levels_modifiers`.`level_id` in (1, 2, 3, 4, 5, 6, 7) - ER_BAD_FIELD_ERROR: Unknown column 'skills_levels_modifiers.level_id' in 'where clause'
    at wrapError (/root/game/node_modules/db-errors/lib/dbErrors.js:19:14)
    at handleExecuteError (/root/game/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1489:32)
    at QueryBuilder.execute (/root/game/node_modules/objection/lib/queryBuilder/QueryBuilder.js:670:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'DBError',
  nativeError:
   { Error: ER_BAD_FIELD_ERROR: Unknown column 'skills_levels_modifiers.level_id' in 'where clause'
       at Query.Sequence._packetToError (/root/game/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
       at Query.ErrorPacket (/root/game/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
       at Protocol._parsePacket (/root/game/node_modules/mysql/lib/protocol/Protocol.js:291:23)
       at Parser._parsePacket (/root/game/node_modules/mysql/lib/protocol/Parser.js:433:10)
       at Parser.write (/root/game/node_modules/mysql/lib/protocol/Parser.js:43:10)
       at Protocol.write (/root/game/node_modules/mysql/lib/protocol/Protocol.js:38:16)
       at Socket.<anonymous> (/root/game/node_modules/mysql/lib/Connection.js:88:28)
       at Socket.<anonymous> (/root/game/node_modules/mysql/lib/Connection.js:526:10)
       at Socket.emit (events.js:198:13)
       at addChunk (_stream_readable.js:288:12)
       --------------------
       at Protocol._enqueue (/root/game/node_modules/mysql/lib/protocol/Protocol.js:144:48)
       at Connection.query (/root/game/node_modules/mysql/lib/Connection.js:198:25)
       at /root/game/node_modules/knex/lib/dialects/mysql/index.js:134:18
       at new Promise (<anonymous>)
       at Client_MySQL._query (/root/game/node_modules/knex/lib/dialects/mysql/index.js:128:12)
       at Client_MySQL.query (/root/game/node_modules/knex/lib/client.js:168:17)
       at Runner.query (/root/game/node_modules/knex/lib/runner.js:151:36)
       at /root/game/node_modules/knex/lib/runner.js:40:23
       at client.acquireConnection.catch.then (/root/game/node_modules/knex/lib/runner.js:277:24)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlMessage:
      'Unknown column \'skills_levels_modifiers.level_id\' in \'where clause\'',
     sqlState: '42S22',
     index: 0,
     sql:
      'select `skills_levels_modifiers`.* from `skills_levels_modifiers` where `skills_levels_modifiers`.`level_id` in (1, 2, 3, 4, 5, 6, 7)' },
  client: 'mysql' }

**Comment by lendsp** [comment]
- Issue detail: some miss field in tables of skills
- Steps to reproduce: setup using guide
- Console error log: posted

**Comment by damian-pastorini** [comment]
Hi @lendsp thanks for reporting, there's a missing part on the upgrade script, the fixed version can be found here:
https://github.com/damian-pastorini/reldens/blob/v4.0.0-beta.17/migrations/production/beta.16.5-sql-update.sql
until I publish the next beta (this week).

Thanks!

**Comment by damian-pastorini** [comment]
Fix released.
