### ISSUE TITLE
Reldens on Plesk

### ISSUE THREAD

**Issue by MBoberski** [damian-pastorini/reldens#247]
I was trying to run engine on my Plesk instance with node support but when I try to create game I get:

```
# yarn reldens createApp my-game
Process exited with non-zero exit code '1'
yarn run v1.22.22
$ /var/www/vhosts/pojegrani.pl/mmorpg.pojegrani.pl/node_modules/.bin/reldens createApp my-game
- Reldens - 
- Use "help" as argument to see all the available commands:
$ node scripts/reldens-commands.js help
- Command "createApp" ready to be executed.
- Theme: my-game
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

warning package.json: No license field
(node:29377) Warning: Closing directory handle on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29377) Warning: Closing directory handle on garbage collection
/var/www/vhosts/pojegrani.pl/mmorpg.pojegrani.pl/node_modules/@reldens/utils/lib/error-manager.js:23
        throw new Error(message);
              ^

Error: Parcel build Game Client process failed.
    at ErrorManager.error (/var/www/vhosts/pojegrani.pl/mmorpg.pojegrani.pl/node_modules/@reldens/utils/lib/error-manager.js:23:15)
    at ThemeManager.buildClient (/var/www/vhosts/pojegrani.pl/mmorpg.pojegrani.pl/node_modules/reldens/lib/game/server/theme-manager.js:323:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ThemeManager.buildSkeleton (/var/www/vhosts/pojegrani.pl/mmorpg.pojegrani.pl/node_modules/reldens/lib/game/server/theme-manager.js:302:9)
    at async ThemeManager.fullRebuild (/var/www/vhosts/pojegrani.pl/mmorpg.pojegrani.pl/node_modules/reldens/lib/game/server/theme-manager.js:417:9)
    at async ThemeManager.createApp (/var/www/vhosts/pojegrani.pl/mmorpg.pojegrani.pl/node_modules/reldens/lib/game/server/theme-manager.js:432:9)
    at async Commander.execute (/var/www/vhosts/pojegrani.pl/mmorpg.pojegrani.pl/node_modules/reldens/bin/commander.js:82:9)

Node.js v18.20.2
error Command failed with exit code 1.
```

I don't hjave npx but yarn should be doin the same job. Any idea why?

**Comment by MBoberski** [comment]
Yeah that worked but no I have:

```
26159/T2w age/Cor/App/Implementation.cpp:221: Could not spawn process for application [/var/www/vhosts/pojegrani.pl/mmorpg.pojegrani.pl](): The application process exited prematurely.
Error ID: df628c21
```

**Comment by MBoberski** [comment]
when I try to start app

**Comment by damian-pastorini** [comment]
I think now you are hitting another known issue but this time is one between nodejs and mysql, you probably need to grant your user with native password, try:
`CREATE USER '<YOUR_USERNAME>'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '<YOUR_PASSWORD>';`
or
`ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'current password'`

**Comment by damian-pastorini** [comment]
I'm closing this, let me know if the issue persist with the latest beta. Thanks for reporting!
